name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: make setup-linux UV_ARGS="--system"
      - run: |
          ollama serve &
          make test UV_ARGS="--system"
