name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: make setup-linux UV_ARGS="--system"
      - run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          make test UV_ARGS="--system"
      - run: make static UV_ARGS="--system"
